// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/images.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImagesService_ImagesV1Upload_FullMethodName = "/golang_blog.ImagesService/ImagesV1Upload"
)

// ImagesServiceClient is the client API for ImagesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImagesServiceClient interface {
	// Uploads an image. Returns image UUID and URL.
	ImagesV1Upload(ctx context.Context, in *V1ImagesUploadRequest, opts ...grpc.CallOption) (*V1ImagesUploadResponse, error)
}

type imagesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImagesServiceClient(cc grpc.ClientConnInterface) ImagesServiceClient {
	return &imagesServiceClient{cc}
}

func (c *imagesServiceClient) ImagesV1Upload(ctx context.Context, in *V1ImagesUploadRequest, opts ...grpc.CallOption) (*V1ImagesUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1ImagesUploadResponse)
	err := c.cc.Invoke(ctx, ImagesService_ImagesV1Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImagesServiceServer is the server API for ImagesService service.
// All implementations must embed UnimplementedImagesServiceServer
// for forward compatibility.
type ImagesServiceServer interface {
	// Uploads an image. Returns image UUID and URL.
	ImagesV1Upload(context.Context, *V1ImagesUploadRequest) (*V1ImagesUploadResponse, error)
	mustEmbedUnimplementedImagesServiceServer()
}

// UnimplementedImagesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImagesServiceServer struct{}

func (UnimplementedImagesServiceServer) ImagesV1Upload(context.Context, *V1ImagesUploadRequest) (*V1ImagesUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImagesV1Upload not implemented")
}
func (UnimplementedImagesServiceServer) mustEmbedUnimplementedImagesServiceServer() {}
func (UnimplementedImagesServiceServer) testEmbeddedByValue()                       {}

// UnsafeImagesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagesServiceServer will
// result in compilation errors.
type UnsafeImagesServiceServer interface {
	mustEmbedUnimplementedImagesServiceServer()
}

func RegisterImagesServiceServer(s grpc.ServiceRegistrar, srv ImagesServiceServer) {
	// If the following call panics, it indicates UnimplementedImagesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImagesService_ServiceDesc, srv)
}

func _ImagesService_ImagesV1Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1ImagesUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServiceServer).ImagesV1Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImagesService_ImagesV1Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServiceServer).ImagesV1Upload(ctx, req.(*V1ImagesUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImagesService_ServiceDesc is the grpc.ServiceDesc for ImagesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImagesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "golang_blog.ImagesService",
	HandlerType: (*ImagesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImagesV1Upload",
			Handler:    _ImagesService_ImagesV1Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/images.proto",
}
