// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/images.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type V1ImagesUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1ImagesUploadRequest) Reset() {
	*x = V1ImagesUploadRequest{}
	mi := &file_api_proto_images_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1ImagesUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1ImagesUploadRequest) ProtoMessage() {}

func (x *V1ImagesUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_images_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1ImagesUploadRequest.ProtoReflect.Descriptor instead.
func (*V1ImagesUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_images_proto_rawDescGZIP(), []int{0}
}

func (x *V1ImagesUploadRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *V1ImagesUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type V1ImagesUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUuid     string                 `protobuf:"bytes,1,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1ImagesUploadResponse) Reset() {
	*x = V1ImagesUploadResponse{}
	mi := &file_api_proto_images_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1ImagesUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1ImagesUploadResponse) ProtoMessage() {}

func (x *V1ImagesUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_images_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1ImagesUploadResponse.ProtoReflect.Descriptor instead.
func (*V1ImagesUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_images_proto_rawDescGZIP(), []int{1}
}

func (x *V1ImagesUploadResponse) GetImageUuid() string {
	if x != nil {
		return x.ImageUuid
	}
	return ""
}

func (x *V1ImagesUploadResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_api_proto_images_proto protoreflect.FileDescriptor

const file_api_proto_images_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/images.proto\x12\vgolang_blog\x1a\x1cgoogle/api/annotations.proto\"Y\n" +
	"\x15V1ImagesUploadRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"T\n" +
	"\x16V1ImagesUploadResponse\x12\x1d\n" +
	"\n" +
	"image_uuid\x18\x01 \x01(\tR\timageUuid\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl2\x88\x01\n" +
	"\rImagesService\x12w\n" +
	"\x0eImagesV1Upload\x12\".golang_blog.V1ImagesUploadRequest\x1a#.golang_blog.V1ImagesUploadResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/images/uploadB*Z(github.com/Gosstik/golang_blog/api/protob\x06proto3"

var (
	file_api_proto_images_proto_rawDescOnce sync.Once
	file_api_proto_images_proto_rawDescData []byte
)

func file_api_proto_images_proto_rawDescGZIP() []byte {
	file_api_proto_images_proto_rawDescOnce.Do(func() {
		file_api_proto_images_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_images_proto_rawDesc), len(file_api_proto_images_proto_rawDesc)))
	})
	return file_api_proto_images_proto_rawDescData
}

var file_api_proto_images_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_images_proto_goTypes = []any{
	(*V1ImagesUploadRequest)(nil),  // 0: golang_blog.V1ImagesUploadRequest
	(*V1ImagesUploadResponse)(nil), // 1: golang_blog.V1ImagesUploadResponse
}
var file_api_proto_images_proto_depIdxs = []int32{
	0, // 0: golang_blog.ImagesService.ImagesV1Upload:input_type -> golang_blog.V1ImagesUploadRequest
	1, // 1: golang_blog.ImagesService.ImagesV1Upload:output_type -> golang_blog.V1ImagesUploadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_images_proto_init() }
func file_api_proto_images_proto_init() {
	if File_api_proto_images_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_images_proto_rawDesc), len(file_api_proto_images_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_images_proto_goTypes,
		DependencyIndexes: file_api_proto_images_proto_depIdxs,
		MessageInfos:      file_api_proto_images_proto_msgTypes,
	}.Build()
	File_api_proto_images_proto = out.File
	file_api_proto_images_proto_goTypes = nil
	file_api_proto_images_proto_depIdxs = nil
}
