// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/posts.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Uuid     string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nickname string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname  string                 `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	// [optional]
	AvatarUrl     string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type BlogPost struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Uuid      string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Author    *User                  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// [optional]
	UpdatedAt  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikesCount int64                `protobuf:"varint,5,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	// [optional]
	ContentText      string   `protobuf:"bytes,6,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	ContentImageUrls []string `protobuf:"bytes,7,rep,name=content_image_urls,json=contentImageUrls,proto3" json:"content_image_urls,omitempty"`
	LikedByMe        bool     `protobuf:"varint,8,opt,name=liked_by_me,json=likedByMe,proto3" json:"liked_by_me,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlogPost) Reset() {
	*x = BlogPost{}
	mi := &file_api_proto_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPost) ProtoMessage() {}

func (x *BlogPost) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPost.ProtoReflect.Descriptor instead.
func (*BlogPost) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{1}
}

func (x *BlogPost) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BlogPost) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *BlogPost) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BlogPost) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BlogPost) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *BlogPost) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *BlogPost) GetContentImageUrls() []string {
	if x != nil {
		return x.ContentImageUrls
	}
	return nil
}

func (x *BlogPost) GetLikedByMe() bool {
	if x != nil {
		return x.LikedByMe
	}
	return false
}

// The value is a base64-encoded JSON string.
// Each endpoint defines its own cursor structure.
// Empty cursor means end of pagination.
type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_api_proto_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{2}
}

func (x *Cursor) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type V1PostsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsListRequest) Reset() {
	*x = V1PostsListRequest{}
	mi := &file_api_proto_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsListRequest) ProtoMessage() {}

func (x *V1PostsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsListRequest.ProtoReflect.Descriptor instead.
func (*V1PostsListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{3}
}

func (x *V1PostsListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *V1PostsListRequest) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type V1PostsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*BlogPost            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsListResponse) Reset() {
	*x = V1PostsListResponse{}
	mi := &file_api_proto_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsListResponse) ProtoMessage() {}

func (x *V1PostsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsListResponse.ProtoReflect.Descriptor instead.
func (*V1PostsListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{4}
}

func (x *V1PostsListResponse) GetPosts() []*BlogPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *V1PostsListResponse) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type V1PostsCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [optional]
	ContentText      string   `protobuf:"bytes,1,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	ContentImageUrls []string `protobuf:"bytes,2,rep,name=content_image_urls,json=contentImageUrls,proto3" json:"content_image_urls,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *V1PostsCreateRequest) Reset() {
	*x = V1PostsCreateRequest{}
	mi := &file_api_proto_posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsCreateRequest) ProtoMessage() {}

func (x *V1PostsCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsCreateRequest.ProtoReflect.Descriptor instead.
func (*V1PostsCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{5}
}

func (x *V1PostsCreateRequest) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *V1PostsCreateRequest) GetContentImageUrls() []string {
	if x != nil {
		return x.ContentImageUrls
	}
	return nil
}

type V1PostsCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *BlogPost              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsCreateResponse) Reset() {
	*x = V1PostsCreateResponse{}
	mi := &file_api_proto_posts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsCreateResponse) ProtoMessage() {}

func (x *V1PostsCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsCreateResponse.ProtoReflect.Descriptor instead.
func (*V1PostsCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{6}
}

func (x *V1PostsCreateResponse) GetPost() *BlogPost {
	if x != nil {
		return x.Post
	}
	return nil
}

type V1PostsEditRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PostUuid string                 `protobuf:"bytes,1,opt,name=post_uuid,json=postUuid,proto3" json:"post_uuid,omitempty"`
	// [optional]
	ContentText string `protobuf:"bytes,2,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	// [optional]
	ContentImageUrls []string `protobuf:"bytes,3,rep,name=content_image_urls,json=contentImageUrls,proto3" json:"content_image_urls,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *V1PostsEditRequest) Reset() {
	*x = V1PostsEditRequest{}
	mi := &file_api_proto_posts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsEditRequest) ProtoMessage() {}

func (x *V1PostsEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsEditRequest.ProtoReflect.Descriptor instead.
func (*V1PostsEditRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{7}
}

func (x *V1PostsEditRequest) GetPostUuid() string {
	if x != nil {
		return x.PostUuid
	}
	return ""
}

func (x *V1PostsEditRequest) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *V1PostsEditRequest) GetContentImageUrls() []string {
	if x != nil {
		return x.ContentImageUrls
	}
	return nil
}

type V1PostsEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *BlogPost              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsEditResponse) Reset() {
	*x = V1PostsEditResponse{}
	mi := &file_api_proto_posts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsEditResponse) ProtoMessage() {}

func (x *V1PostsEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsEditResponse.ProtoReflect.Descriptor instead.
func (*V1PostsEditResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{8}
}

func (x *V1PostsEditResponse) GetPost() *BlogPost {
	if x != nil {
		return x.Post
	}
	return nil
}

type V1PostsDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUuid      string                 `protobuf:"bytes,1,opt,name=post_uuid,json=postUuid,proto3" json:"post_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsDeleteRequest) Reset() {
	*x = V1PostsDeleteRequest{}
	mi := &file_api_proto_posts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsDeleteRequest) ProtoMessage() {}

func (x *V1PostsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsDeleteRequest.ProtoReflect.Descriptor instead.
func (*V1PostsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{9}
}

func (x *V1PostsDeleteRequest) GetPostUuid() string {
	if x != nil {
		return x.PostUuid
	}
	return ""
}

type V1PostsDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsDeleteResponse) Reset() {
	*x = V1PostsDeleteResponse{}
	mi := &file_api_proto_posts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsDeleteResponse) ProtoMessage() {}

func (x *V1PostsDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsDeleteResponse.ProtoReflect.Descriptor instead.
func (*V1PostsDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{10}
}

type V1PostsLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUuid      string                 `protobuf:"bytes,1,opt,name=post_uuid,json=postUuid,proto3" json:"post_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsLikeRequest) Reset() {
	*x = V1PostsLikeRequest{}
	mi := &file_api_proto_posts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsLikeRequest) ProtoMessage() {}

func (x *V1PostsLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsLikeRequest.ProtoReflect.Descriptor instead.
func (*V1PostsLikeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{11}
}

func (x *V1PostsLikeRequest) GetPostUuid() string {
	if x != nil {
		return x.PostUuid
	}
	return ""
}

type V1PostsLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikesCount    int64                  `protobuf:"varint,1,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsLikeResponse) Reset() {
	*x = V1PostsLikeResponse{}
	mi := &file_api_proto_posts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsLikeResponse) ProtoMessage() {}

func (x *V1PostsLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsLikeResponse.ProtoReflect.Descriptor instead.
func (*V1PostsLikeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{12}
}

func (x *V1PostsLikeResponse) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type V1PostsUnlikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUuid      string                 `protobuf:"bytes,1,opt,name=post_uuid,json=postUuid,proto3" json:"post_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsUnlikeRequest) Reset() {
	*x = V1PostsUnlikeRequest{}
	mi := &file_api_proto_posts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsUnlikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsUnlikeRequest) ProtoMessage() {}

func (x *V1PostsUnlikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsUnlikeRequest.ProtoReflect.Descriptor instead.
func (*V1PostsUnlikeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{13}
}

func (x *V1PostsUnlikeRequest) GetPostUuid() string {
	if x != nil {
		return x.PostUuid
	}
	return ""
}

type V1PostsUnlikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikesCount    int64                  `protobuf:"varint,1,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsUnlikeResponse) Reset() {
	*x = V1PostsUnlikeResponse{}
	mi := &file_api_proto_posts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsUnlikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsUnlikeResponse) ProtoMessage() {}

func (x *V1PostsUnlikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsUnlikeResponse.ProtoReflect.Descriptor instead.
func (*V1PostsUnlikeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{14}
}

func (x *V1PostsUnlikeResponse) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type V1PostsLikesListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUuid      string                 `protobuf:"bytes,1,opt,name=post_uuid,json=postUuid,proto3" json:"post_uuid,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsLikesListUsersRequest) Reset() {
	*x = V1PostsLikesListUsersRequest{}
	mi := &file_api_proto_posts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsLikesListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsLikesListUsersRequest) ProtoMessage() {}

func (x *V1PostsLikesListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsLikesListUsersRequest.ProtoReflect.Descriptor instead.
func (*V1PostsLikesListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{15}
}

func (x *V1PostsLikesListUsersRequest) GetPostUuid() string {
	if x != nil {
		return x.PostUuid
	}
	return ""
}

func (x *V1PostsLikesListUsersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *V1PostsLikesListUsersRequest) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type V1PostsLikesListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PostsLikesListUsersResponse) Reset() {
	*x = V1PostsLikesListUsersResponse{}
	mi := &file_api_proto_posts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PostsLikesListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PostsLikesListUsersResponse) ProtoMessage() {}

func (x *V1PostsLikesListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_posts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PostsLikesListUsersResponse.ProtoReflect.Descriptor instead.
func (*V1PostsLikesListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_posts_proto_rawDescGZIP(), []int{16}
}

func (x *V1PostsLikesListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *V1PostsLikesListUsersResponse) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

var File_api_proto_posts_proto protoreflect.FileDescriptor

const file_api_proto_posts_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/posts.proto\x12\vgolang_blog\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x04 \x01(\tR\asurname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\"\xd1\x02\n" +
	"\bBlogPost\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12)\n" +
	"\x06author\x18\x02 \x01(\v2\x11.golang_blog.UserR\x06author\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vlikes_count\x18\x05 \x01(\x03R\n" +
	"likesCount\x12!\n" +
	"\fcontent_text\x18\x06 \x01(\tR\vcontentText\x12,\n" +
	"\x12content_image_urls\x18\a \x03(\tR\x10contentImageUrls\x12\x1e\n" +
	"\vliked_by_me\x18\b \x01(\bR\tlikedByMe\"\x1e\n" +
	"\x06Cursor\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"W\n" +
	"\x12V1PostsListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12+\n" +
	"\x06cursor\x18\x02 \x01(\v2\x13.golang_blog.CursorR\x06cursor\"o\n" +
	"\x13V1PostsListResponse\x12+\n" +
	"\x05posts\x18\x01 \x03(\v2\x15.golang_blog.BlogPostR\x05posts\x12+\n" +
	"\x06cursor\x18\x02 \x01(\v2\x13.golang_blog.CursorR\x06cursor\"g\n" +
	"\x14V1PostsCreateRequest\x12!\n" +
	"\fcontent_text\x18\x01 \x01(\tR\vcontentText\x12,\n" +
	"\x12content_image_urls\x18\x02 \x03(\tR\x10contentImageUrls\"B\n" +
	"\x15V1PostsCreateResponse\x12)\n" +
	"\x04post\x18\x01 \x01(\v2\x15.golang_blog.BlogPostR\x04post\"\x82\x01\n" +
	"\x12V1PostsEditRequest\x12\x1b\n" +
	"\tpost_uuid\x18\x01 \x01(\tR\bpostUuid\x12!\n" +
	"\fcontent_text\x18\x02 \x01(\tR\vcontentText\x12,\n" +
	"\x12content_image_urls\x18\x03 \x03(\tR\x10contentImageUrls\"@\n" +
	"\x13V1PostsEditResponse\x12)\n" +
	"\x04post\x18\x01 \x01(\v2\x15.golang_blog.BlogPostR\x04post\"3\n" +
	"\x14V1PostsDeleteRequest\x12\x1b\n" +
	"\tpost_uuid\x18\x01 \x01(\tR\bpostUuid\"\x17\n" +
	"\x15V1PostsDeleteResponse\"1\n" +
	"\x12V1PostsLikeRequest\x12\x1b\n" +
	"\tpost_uuid\x18\x01 \x01(\tR\bpostUuid\"6\n" +
	"\x13V1PostsLikeResponse\x12\x1f\n" +
	"\vlikes_count\x18\x01 \x01(\x03R\n" +
	"likesCount\"3\n" +
	"\x14V1PostsUnlikeRequest\x12\x1b\n" +
	"\tpost_uuid\x18\x01 \x01(\tR\bpostUuid\"8\n" +
	"\x15V1PostsUnlikeResponse\x12\x1f\n" +
	"\vlikes_count\x18\x01 \x01(\x03R\n" +
	"likesCount\"~\n" +
	"\x1cV1PostsLikesListUsersRequest\x12\x1b\n" +
	"\tpost_uuid\x18\x01 \x01(\tR\bpostUuid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12+\n" +
	"\x06cursor\x18\x03 \x01(\v2\x13.golang_blog.CursorR\x06cursor\"u\n" +
	"\x1dV1PostsLikesListUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.golang_blog.UserR\x05users\x12+\n" +
	"\x06cursor\x18\x02 \x01(\v2\x13.golang_blog.CursorR\x06cursor2\xce\x06\n" +
	"\fPostsService\x12c\n" +
	"\vPostsV1List\x12\x1f.golang_blog.V1PostsListRequest\x1a .golang_blog.V1PostsListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/posts\x12k\n" +
	"\fPostV1Create\x12!.golang_blog.V1PostsCreateRequest\x1a\".golang_blog.V1PostsCreateResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/posts\x12q\n" +
	"\n" +
	"PostV1Edit\x12\x1f.golang_blog.V1PostsEditRequest\x1a .golang_blog.V1PostsEditResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/v1/posts/{post_uuid}\x12t\n" +
	"\fPostV1Delete\x12!.golang_blog.V1PostsDeleteRequest\x1a\".golang_blog.V1PostsDeleteResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/posts/{post_uuid}\x12s\n" +
	"\n" +
	"PostV1Like\x12\x1f.golang_blog.V1PostsLikeRequest\x1a .golang_blog.V1PostsLikeResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v1/posts/{post_uuid}/like\x12y\n" +
	"\fPostV1Unlike\x12!.golang_blog.V1PostsUnlikeRequest\x1a\".golang_blog.V1PostsUnlikeResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/posts/{post_uuid}/like\x12\x92\x01\n" +
	"\x14PostV1LikesListUsers\x12).golang_blog.V1PostsLikesListUsersRequest\x1a*.golang_blog.V1PostsLikesListUsersResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/posts/{post_uuid}/likesB*Z(github.com/Gosstik/golang_blog/api/protob\x06proto3"

var (
	file_api_proto_posts_proto_rawDescOnce sync.Once
	file_api_proto_posts_proto_rawDescData []byte
)

func file_api_proto_posts_proto_rawDescGZIP() []byte {
	file_api_proto_posts_proto_rawDescOnce.Do(func() {
		file_api_proto_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_posts_proto_rawDesc), len(file_api_proto_posts_proto_rawDesc)))
	})
	return file_api_proto_posts_proto_rawDescData
}

var file_api_proto_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_posts_proto_goTypes = []any{
	(*User)(nil),                          // 0: golang_blog.User
	(*BlogPost)(nil),                      // 1: golang_blog.BlogPost
	(*Cursor)(nil),                        // 2: golang_blog.Cursor
	(*V1PostsListRequest)(nil),            // 3: golang_blog.V1PostsListRequest
	(*V1PostsListResponse)(nil),           // 4: golang_blog.V1PostsListResponse
	(*V1PostsCreateRequest)(nil),          // 5: golang_blog.V1PostsCreateRequest
	(*V1PostsCreateResponse)(nil),         // 6: golang_blog.V1PostsCreateResponse
	(*V1PostsEditRequest)(nil),            // 7: golang_blog.V1PostsEditRequest
	(*V1PostsEditResponse)(nil),           // 8: golang_blog.V1PostsEditResponse
	(*V1PostsDeleteRequest)(nil),          // 9: golang_blog.V1PostsDeleteRequest
	(*V1PostsDeleteResponse)(nil),         // 10: golang_blog.V1PostsDeleteResponse
	(*V1PostsLikeRequest)(nil),            // 11: golang_blog.V1PostsLikeRequest
	(*V1PostsLikeResponse)(nil),           // 12: golang_blog.V1PostsLikeResponse
	(*V1PostsUnlikeRequest)(nil),          // 13: golang_blog.V1PostsUnlikeRequest
	(*V1PostsUnlikeResponse)(nil),         // 14: golang_blog.V1PostsUnlikeResponse
	(*V1PostsLikesListUsersRequest)(nil),  // 15: golang_blog.V1PostsLikesListUsersRequest
	(*V1PostsLikesListUsersResponse)(nil), // 16: golang_blog.V1PostsLikesListUsersResponse
	(*timestamp.Timestamp)(nil),           // 17: google.protobuf.Timestamp
}
var file_api_proto_posts_proto_depIdxs = []int32{
	0,  // 0: golang_blog.BlogPost.author:type_name -> golang_blog.User
	17, // 1: golang_blog.BlogPost.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: golang_blog.BlogPost.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: golang_blog.V1PostsListRequest.cursor:type_name -> golang_blog.Cursor
	1,  // 4: golang_blog.V1PostsListResponse.posts:type_name -> golang_blog.BlogPost
	2,  // 5: golang_blog.V1PostsListResponse.cursor:type_name -> golang_blog.Cursor
	1,  // 6: golang_blog.V1PostsCreateResponse.post:type_name -> golang_blog.BlogPost
	1,  // 7: golang_blog.V1PostsEditResponse.post:type_name -> golang_blog.BlogPost
	2,  // 8: golang_blog.V1PostsLikesListUsersRequest.cursor:type_name -> golang_blog.Cursor
	0,  // 9: golang_blog.V1PostsLikesListUsersResponse.users:type_name -> golang_blog.User
	2,  // 10: golang_blog.V1PostsLikesListUsersResponse.cursor:type_name -> golang_blog.Cursor
	3,  // 11: golang_blog.PostsService.PostsV1List:input_type -> golang_blog.V1PostsListRequest
	5,  // 12: golang_blog.PostsService.PostV1Create:input_type -> golang_blog.V1PostsCreateRequest
	7,  // 13: golang_blog.PostsService.PostV1Edit:input_type -> golang_blog.V1PostsEditRequest
	9,  // 14: golang_blog.PostsService.PostV1Delete:input_type -> golang_blog.V1PostsDeleteRequest
	11, // 15: golang_blog.PostsService.PostV1Like:input_type -> golang_blog.V1PostsLikeRequest
	13, // 16: golang_blog.PostsService.PostV1Unlike:input_type -> golang_blog.V1PostsUnlikeRequest
	15, // 17: golang_blog.PostsService.PostV1LikesListUsers:input_type -> golang_blog.V1PostsLikesListUsersRequest
	4,  // 18: golang_blog.PostsService.PostsV1List:output_type -> golang_blog.V1PostsListResponse
	6,  // 19: golang_blog.PostsService.PostV1Create:output_type -> golang_blog.V1PostsCreateResponse
	8,  // 20: golang_blog.PostsService.PostV1Edit:output_type -> golang_blog.V1PostsEditResponse
	10, // 21: golang_blog.PostsService.PostV1Delete:output_type -> golang_blog.V1PostsDeleteResponse
	12, // 22: golang_blog.PostsService.PostV1Like:output_type -> golang_blog.V1PostsLikeResponse
	14, // 23: golang_blog.PostsService.PostV1Unlike:output_type -> golang_blog.V1PostsUnlikeResponse
	16, // 24: golang_blog.PostsService.PostV1LikesListUsers:output_type -> golang_blog.V1PostsLikesListUsersResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_posts_proto_init() }
func file_api_proto_posts_proto_init() {
	if File_api_proto_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_posts_proto_rawDesc), len(file_api_proto_posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_posts_proto_goTypes,
		DependencyIndexes: file_api_proto_posts_proto_depIdxs,
		MessageInfos:      file_api_proto_posts_proto_msgTypes,
	}.Build()
	File_api_proto_posts_proto = out.File
	file_api_proto_posts_proto_goTypes = nil
	file_api_proto_posts_proto_depIdxs = nil
}
