// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/posts.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostsService_PostsV1List_FullMethodName          = "/golang_blog.PostsService/PostsV1List"
	PostsService_PostV1Create_FullMethodName         = "/golang_blog.PostsService/PostV1Create"
	PostsService_PostV1Edit_FullMethodName           = "/golang_blog.PostsService/PostV1Edit"
	PostsService_PostV1Delete_FullMethodName         = "/golang_blog.PostsService/PostV1Delete"
	PostsService_PostV1Like_FullMethodName           = "/golang_blog.PostsService/PostV1Like"
	PostsService_PostV1Unlike_FullMethodName         = "/golang_blog.PostsService/PostV1Unlike"
	PostsService_PostV1LikesListUsers_FullMethodName = "/golang_blog.PostsService/PostV1LikesListUsers"
)

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostsServiceClient interface {
	// Returns a paginated list of posts ordered by creation time.
	PostsV1List(ctx context.Context, in *V1PostsListRequest, opts ...grpc.CallOption) (*V1PostsListResponse, error)
	// Creates a new blog post. Author is determined from X-User-Uuid header.
	PostV1Create(ctx context.Context, in *V1PostsCreateRequest, opts ...grpc.CallOption) (*V1PostsCreateResponse, error)
	// Edits an existing blog post.
	PostV1Edit(ctx context.Context, in *V1PostsEditRequest, opts ...grpc.CallOption) (*V1PostsEditResponse, error)
	// Deletes a blog post.
	PostV1Delete(ctx context.Context, in *V1PostsDeleteRequest, opts ...grpc.CallOption) (*V1PostsDeleteResponse, error)
	// Likes a post. User is determined from X-User-Uuid header.
	PostV1Like(ctx context.Context, in *V1PostsLikeRequest, opts ...grpc.CallOption) (*V1PostsLikeResponse, error)
	// Removes a like from a post. User is determined from X-User-Uuid header.
	PostV1Unlike(ctx context.Context, in *V1PostsUnlikeRequest, opts ...grpc.CallOption) (*V1PostsUnlikeResponse, error)
	// Returns a list of users who liked a specific post.
	PostV1LikesListUsers(ctx context.Context, in *V1PostsLikesListUsersRequest, opts ...grpc.CallOption) (*V1PostsLikesListUsersResponse, error)
}

type postsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostsServiceClient(cc grpc.ClientConnInterface) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) PostsV1List(ctx context.Context, in *V1PostsListRequest, opts ...grpc.CallOption) (*V1PostsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1PostsListResponse)
	err := c.cc.Invoke(ctx, PostsService_PostsV1List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) PostV1Create(ctx context.Context, in *V1PostsCreateRequest, opts ...grpc.CallOption) (*V1PostsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1PostsCreateResponse)
	err := c.cc.Invoke(ctx, PostsService_PostV1Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) PostV1Edit(ctx context.Context, in *V1PostsEditRequest, opts ...grpc.CallOption) (*V1PostsEditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1PostsEditResponse)
	err := c.cc.Invoke(ctx, PostsService_PostV1Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) PostV1Delete(ctx context.Context, in *V1PostsDeleteRequest, opts ...grpc.CallOption) (*V1PostsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1PostsDeleteResponse)
	err := c.cc.Invoke(ctx, PostsService_PostV1Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) PostV1Like(ctx context.Context, in *V1PostsLikeRequest, opts ...grpc.CallOption) (*V1PostsLikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1PostsLikeResponse)
	err := c.cc.Invoke(ctx, PostsService_PostV1Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) PostV1Unlike(ctx context.Context, in *V1PostsUnlikeRequest, opts ...grpc.CallOption) (*V1PostsUnlikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1PostsUnlikeResponse)
	err := c.cc.Invoke(ctx, PostsService_PostV1Unlike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) PostV1LikesListUsers(ctx context.Context, in *V1PostsLikesListUsersRequest, opts ...grpc.CallOption) (*V1PostsLikesListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V1PostsLikesListUsersResponse)
	err := c.cc.Invoke(ctx, PostsService_PostV1LikesListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
// All implementations must embed UnimplementedPostsServiceServer
// for forward compatibility.
type PostsServiceServer interface {
	// Returns a paginated list of posts ordered by creation time.
	PostsV1List(context.Context, *V1PostsListRequest) (*V1PostsListResponse, error)
	// Creates a new blog post. Author is determined from X-User-Uuid header.
	PostV1Create(context.Context, *V1PostsCreateRequest) (*V1PostsCreateResponse, error)
	// Edits an existing blog post.
	PostV1Edit(context.Context, *V1PostsEditRequest) (*V1PostsEditResponse, error)
	// Deletes a blog post.
	PostV1Delete(context.Context, *V1PostsDeleteRequest) (*V1PostsDeleteResponse, error)
	// Likes a post. User is determined from X-User-Uuid header.
	PostV1Like(context.Context, *V1PostsLikeRequest) (*V1PostsLikeResponse, error)
	// Removes a like from a post. User is determined from X-User-Uuid header.
	PostV1Unlike(context.Context, *V1PostsUnlikeRequest) (*V1PostsUnlikeResponse, error)
	// Returns a list of users who liked a specific post.
	PostV1LikesListUsers(context.Context, *V1PostsLikesListUsersRequest) (*V1PostsLikesListUsersResponse, error)
	mustEmbedUnimplementedPostsServiceServer()
}

// UnimplementedPostsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostsServiceServer struct{}

func (UnimplementedPostsServiceServer) PostsV1List(context.Context, *V1PostsListRequest) (*V1PostsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostsV1List not implemented")
}
func (UnimplementedPostsServiceServer) PostV1Create(context.Context, *V1PostsCreateRequest) (*V1PostsCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostV1Create not implemented")
}
func (UnimplementedPostsServiceServer) PostV1Edit(context.Context, *V1PostsEditRequest) (*V1PostsEditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostV1Edit not implemented")
}
func (UnimplementedPostsServiceServer) PostV1Delete(context.Context, *V1PostsDeleteRequest) (*V1PostsDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostV1Delete not implemented")
}
func (UnimplementedPostsServiceServer) PostV1Like(context.Context, *V1PostsLikeRequest) (*V1PostsLikeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostV1Like not implemented")
}
func (UnimplementedPostsServiceServer) PostV1Unlike(context.Context, *V1PostsUnlikeRequest) (*V1PostsUnlikeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostV1Unlike not implemented")
}
func (UnimplementedPostsServiceServer) PostV1LikesListUsers(context.Context, *V1PostsLikesListUsersRequest) (*V1PostsLikesListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostV1LikesListUsers not implemented")
}
func (UnimplementedPostsServiceServer) mustEmbedUnimplementedPostsServiceServer() {}
func (UnimplementedPostsServiceServer) testEmbeddedByValue()                      {}

// UnsafePostsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostsServiceServer will
// result in compilation errors.
type UnsafePostsServiceServer interface {
	mustEmbedUnimplementedPostsServiceServer()
}

func RegisterPostsServiceServer(s grpc.ServiceRegistrar, srv PostsServiceServer) {
	// If the following call panics, it indicates UnimplementedPostsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostsService_ServiceDesc, srv)
}

func _PostsService_PostsV1List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1PostsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PostsV1List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PostsV1List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PostsV1List(ctx, req.(*V1PostsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_PostV1Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1PostsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PostV1Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PostV1Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PostV1Create(ctx, req.(*V1PostsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_PostV1Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1PostsEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PostV1Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PostV1Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PostV1Edit(ctx, req.(*V1PostsEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_PostV1Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1PostsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PostV1Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PostV1Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PostV1Delete(ctx, req.(*V1PostsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_PostV1Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1PostsLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PostV1Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PostV1Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PostV1Like(ctx, req.(*V1PostsLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_PostV1Unlike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1PostsUnlikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PostV1Unlike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PostV1Unlike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PostV1Unlike(ctx, req.(*V1PostsUnlikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_PostV1LikesListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V1PostsLikesListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PostV1LikesListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PostV1LikesListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PostV1LikesListUsers(ctx, req.(*V1PostsLikesListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostsService_ServiceDesc is the grpc.ServiceDesc for PostsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "golang_blog.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostsV1List",
			Handler:    _PostsService_PostsV1List_Handler,
		},
		{
			MethodName: "PostV1Create",
			Handler:    _PostsService_PostV1Create_Handler,
		},
		{
			MethodName: "PostV1Edit",
			Handler:    _PostsService_PostV1Edit_Handler,
		},
		{
			MethodName: "PostV1Delete",
			Handler:    _PostsService_PostV1Delete_Handler,
		},
		{
			MethodName: "PostV1Like",
			Handler:    _PostsService_PostV1Like_Handler,
		},
		{
			MethodName: "PostV1Unlike",
			Handler:    _PostsService_PostV1Unlike_Handler,
		},
		{
			MethodName: "PostV1LikesListUsers",
			Handler:    _PostsService_PostV1LikesListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/posts.proto",
}
